### ISSUE TITLE
BeautifulSoup name error 

### ISSUE THREAD

**Issue by harshalkondke** [0xPrateek/Stardox#53]
Traceback (most recent call last):
  File "stardox.py", line 346, in <module>
    stardox(repository_link, verbose, max_threads=16)
  File "stardox.py", line 232, in stardox
    soup1 = BeautifulSoup(html, "lxml")
NameError: name 'BeautifulSoup' is not defined

**Comment by 0xPrateek** [comment]
Install BeautifulSoup first.
`pip install beautifulsoup4`
